services:
  postgres:
    image: postgres:15.1
    ports:
      - 5433:5432
    volumes:
      - /data/postgres:/data/postgres
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.docker

  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - redis:/data

  api:
    build:
      dockerfile: dev.Dockerfile
      context: .
    env_file:
      - .env.docker
    ports:
      - 5001:5000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/app
      - ignore:/usr/src/app/node_modules/

volumes:
  ignore:
  redis:
    driver: local
