export enum ErrorEnum {
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_FIRST_NAME = 'INVALID_FIRST_NAME',
  INVALID_LAST_NAME = 'INVALID_LAST_NAME',
  INVALID_USERNAME = 'INVALID_USERNAME',
  INVALID_HOST = 'INVALID_HOST',
  SSH_CONNECTION_FAILS = 'SSH_CONNECTION_FAILS',
}
