export enum ErrorEnum {
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_FIRST_NAME = 'INVALID_FIRST_NAME',
  INVALID_LAST_NAME = 'INVALID_LAST_NAME',
  INVALID_USERNAME = 'INVALID_USERNAME',
  INVALID_HOST = 'INVALID_HOST',
  INCORRECT_SSH_RESPONSE = 'INCORRECT_SSH_RESPONSE',
}
